package com.bissbilanz.model

import kotlinx.serialization.Serializable

@Serializable
data class Food(
    val id: String,
    val userId: String,
    val name: String,
    val brand: String? = null,
    val servingSize: Double,
    val servingUnit: ServingUnit,
    val calories: Double,
    val protein: Double,
    val carbs: Double,
    val fat: Double,
    val fiber: Double,
    // Extended nutrients
    val saturatedFat: Double? = null,
    val monounsaturatedFat: Double? = null,
    val polyunsaturatedFat: Double? = null,
    val transFat: Double? = null,
    val cholesterol: Double? = null,
    val omega3: Double? = null,
    val omega6: Double? = null,
    val sugar: Double? = null,
    val addedSugars: Double? = null,
    val sugarAlcohols: Double? = null,
    val starch: Double? = null,
    val sodium: Double? = null,
    val potassium: Double? = null,
    val calcium: Double? = null,
    val iron: Double? = null,
    val magnesium: Double? = null,
    val phosphorus: Double? = null,
    val zinc: Double? = null,
    val copper: Double? = null,
    val manganese: Double? = null,
    val selenium: Double? = null,
    val iodine: Double? = null,
    val fluoride: Double? = null,
    val chromium: Double? = null,
    val molybdenum: Double? = null,
    val chloride: Double? = null,
    val vitaminA: Double? = null,
    val vitaminC: Double? = null,
    val vitaminD: Double? = null,
    val vitaminE: Double? = null,
    val vitaminK: Double? = null,
    val vitaminB1: Double? = null,
    val vitaminB2: Double? = null,
    val vitaminB3: Double? = null,
    val vitaminB5: Double? = null,
    val vitaminB6: Double? = null,
    val vitaminB7: Double? = null,
    val vitaminB9: Double? = null,
    val vitaminB12: Double? = null,
    val caffeine: Double? = null,
    val alcohol: Double? = null,
    val water: Double? = null,
    val salt: Double? = null,
    // Metadata
    val barcode: String? = null,
    val isFavorite: Boolean = false,
    val nutriScore: String? = null,
    val novaGroup: Int? = null,
    val additives: List<String>? = null,
    val ingredientsText: String? = null,
    val imageUrl: String? = null,
    val createdAt: String? = null,
    val updatedAt: String? = null,
)

@Serializable
data class FoodCreate(
    val name: String,
    val brand: String? = null,
    val servingSize: Double,
    val servingUnit: ServingUnit,
    val calories: Double,
    val protein: Double,
    val carbs: Double,
    val fat: Double,
    val fiber: Double,
    val saturatedFat: Double? = null,
    val monounsaturatedFat: Double? = null,
    val polyunsaturatedFat: Double? = null,
    val transFat: Double? = null,
    val cholesterol: Double? = null,
    val omega3: Double? = null,
    val omega6: Double? = null,
    val sugar: Double? = null,
    val addedSugars: Double? = null,
    val sugarAlcohols: Double? = null,
    val starch: Double? = null,
    val sodium: Double? = null,
    val potassium: Double? = null,
    val calcium: Double? = null,
    val iron: Double? = null,
    val magnesium: Double? = null,
    val phosphorus: Double? = null,
    val zinc: Double? = null,
    val copper: Double? = null,
    val manganese: Double? = null,
    val selenium: Double? = null,
    val iodine: Double? = null,
    val fluoride: Double? = null,
    val chromium: Double? = null,
    val molybdenum: Double? = null,
    val chloride: Double? = null,
    val vitaminA: Double? = null,
    val vitaminC: Double? = null,
    val vitaminD: Double? = null,
    val vitaminE: Double? = null,
    val vitaminK: Double? = null,
    val vitaminB1: Double? = null,
    val vitaminB2: Double? = null,
    val vitaminB3: Double? = null,
    val vitaminB5: Double? = null,
    val vitaminB6: Double? = null,
    val vitaminB7: Double? = null,
    val vitaminB9: Double? = null,
    val vitaminB12: Double? = null,
    val caffeine: Double? = null,
    val alcohol: Double? = null,
    val water: Double? = null,
    val salt: Double? = null,
    val barcode: String? = null,
    val isFavorite: Boolean? = null,
    val nutriScore: String? = null,
    val novaGroup: Int? = null,
    val additives: List<String>? = null,
    val ingredientsText: String? = null,
    val imageUrl: String? = null,
)

@Serializable
data class FoodsResponse(
    val foods: List<Food>,
    val total: Int = 0,
)

@Serializable
data class FoodResponse(
    val food: Food? = null,
)
