export const toolNames = [
	'get_daily_status',
	'create_food',
	'update_food',
	'delete_food',
	'list_recent_foods',
	'create_recipe',
	'update_recipe',
	'delete_recipe',
	'log_food',
	'search_foods',
	'get_supplement_status',
	'log_supplement',
	'create_supplement',
	'list_supplements',
	'update_supplement',
	'delete_supplement',
	'unlog_supplement',
	'list_entries',
	'update_entry',
	'delete_entry',
	'get_goals',
	'update_goals',
	'list_recipes',
	'get_recipe',
	'get_food',
	'list_favorites',
	'log_weight',
	'update_weight',
	'delete_weight',
	'get_weight',
	'get_weekly_stats',
	'get_monthly_stats',
	'get_daily_breakdown',
	'get_meal_breakdown',
	'get_top_foods',
	'get_streaks',
	'get_maintenance_calories',
	'copy_entries',
	'find_food_by_barcode',
	'search_openfoodfacts',
	'log_sleep',
	'get_sleep',
	'update_sleep',
	'delete_sleep',
	// Analytics
	'get_food_diversity',
	'get_meal_timing',
	'get_sleep_food_correlation',
	'get_weight_food_series',
	'get_extended_nutrients',
	'get_daily_nutrients',
	// Meal types
	'list_meal_types',
	// Supplement history
	'get_supplement_history',
	// Day properties
	'get_day_properties',
	'set_day_properties',
	'delete_day_properties',
	// Calendar stats
	'get_calendar_stats',
	// AI task queue
	'list_ai_tasks',
	'get_ai_task',
	'complete_ai_task',
	'dismiss_ai_task'
] as const;
