/**
 * Generates the broad cross-platform fixtures in tests/fixtures/shared/generated-*.json
 * by running the TypeScript implementations (the server is the source of truth).
 *
 *   bun run shared:generate   rewrite the files
 *   bun run shared:check      fail when a file is stale (CI)
 *
 * The hand-written fixtures next to them (recipe-math.json, goal-rules.json, ...) pin
 * individual reviewed cases; these grids sweep the input space so a platform that
 * rounds, converts or orders differently fails on a case nobody thought to write.
 * See tests/fixtures/shared/README.md.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';

import { runGeneratedCase } from '../../tests/shared-fixtures/runners';
import { servingUnitValues } from '../../src/lib/units';

type Platform = 'web' | 'kotlin' | 'swift';
type Divergence = { platform: Platform; expected: unknown; reason: string };
type Case = {
	fn: string;
	name: string;
	input: Record<string, unknown>;
	expected: unknown;
	divergences?: Divergence[];
};
type FixtureFile = {
	$comment: string;
	tolerance: number;
	implementations: Record<string, Platform[]>;
	cases: Case[];
};

const ALL: Platform[] = ['web', 'kotlin', 'swift'];
const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../../tests/fixtures/shared');

const make = (fn: string, name: string, input: Record<string, unknown>): Case => ({
	fn,
	name,
	input,
	expected: runGeneratedCase(fn, input)
});

// --- unit conversion ---------------------------------------------------------

function unitConversion(): FixtureFile {
	const cases: Case[] = [];
	for (const from of servingUnitValues) {
		for (const to of servingUnitValues) {
			for (const quantity of [0.5, 1, 250]) {
				cases.push(
					make('convertQuantityForMacros', `${from}_to_${to}_x${quantity}`, { quantity, from, to })
				);
			}
		}
	}
	return {
		$comment:
			'Generated by scripts/shared-fixtures/generate.ts from src/lib/units.ts: every serving unit converted to every other (cross-dimension pairs fall back to the raw quantity).',
		tolerance: 1e-9,
		implementations: { convertQuantityForMacros: ALL },
		cases
	};
}

// --- recipe per-serving math and cooked-weight yield -----------------------------

const rice = {
	servingSize: 100,
	servingUnit: 'g',
	calories: 130,
	protein: 2.7,
	carbs: 28,
	fat: 0.3,
	fiber: 0.4
};
const oil = {
	servingSize: 1,
	servingUnit: 'tbsp',
	calories: 120,
	protein: 0,
	carbs: 0,
	fat: 14,
	fiber: 0
};
const milk = {
	servingSize: 250,
	servingUnit: 'ml',
	calories: 150,
	protein: 8,
	carbs: 12,
	fat: 8,
	fiber: 0
};
const oats = {
	servingSize: 40,
	servingUnit: 'g',
	calories: 150,
	protein: 5,
	carbs: 27,
	fat: 2.5,
	fiber: 4
};

function recipeMath(): FixtureFile {
	const cases: Case[] = [];

	const recipes: Record<string, { ingredients: Record<string, unknown>[] }> = {
		single_same_unit: { ingredients: [{ quantity: 200, servingUnit: 'g', food: rice }] },
		mixed_units: {
			ingredients: [
				{ quantity: 0.5, servingUnit: 'kg', food: rice },
				{ quantity: 2, servingUnit: 'tbsp', food: oil },
				{ quantity: 1, servingUnit: 'cup', food: milk }
			]
		},
		ounces_and_litres: {
			ingredients: [
				{ quantity: 4, servingUnit: 'oz', food: oats },
				{ quantity: 0.3, servingUnit: 'l', food: milk }
			]
		},
		cross_dimension_legacy_row: {
			ingredients: [
				{ quantity: 30, servingUnit: 'ml', food: oats },
				{ quantity: 100, servingUnit: 'g', food: rice }
			]
		},
		no_ingredients: { ingredients: [] }
	};
	for (const [name, recipe] of Object.entries(recipes)) {
		for (const totalServings of [0.25, 0.5, 1, 1.5, 3, 4, 12]) {
			const c = make('recipeMacros', `${name}_serves_${totalServings}`, {
				totalServings,
				...recipe
			});
			if (recipe.ingredients.length === 0) {
				c.divergences = [
					{
						platform: 'kotlin',
						expected: null,
						reason:
							'computeRecipePerServingMacros returns null for a recipe without ingredients (callers keep the cached values); web and iOS sum to zero'
					}
				];
			}
			cases.push(c);
		}
	}

	for (const totalServings of [0.25, 0.5, 1, 3, 4]) {
		for (const cookedWeight of [null, 0, 300, 1000]) {
			const tag = `${cookedWeight ?? 'none'}g_serves_${totalServings}`;
			cases.push(make('cookedWeightServingSize', tag, { cookedWeight, totalServings }));
			cases.push(
				make('caloriesPerHundredGrams', tag, { calories: 1800, cookedWeight, totalServings })
			);
			for (const grams of [0, 50, 150, 1000]) {
				cases.push(
					make('gramsToServings', `${grams}g_of_${tag}`, { grams, cookedWeight, totalServings })
				);
			}
		}
	}

	return {
		$comment:
			'Generated by scripts/shared-fixtures/generate.ts from src/lib/analytics/aggregation.ts and src/lib/utils/recipe-yield.ts: recipe macros across unit mixes and serving counts (including recipes under one serving) and the cooked-weight yield helpers.',
		tolerance: 1e-9,
		implementations: {
			recipeMacros: ALL,
			cookedWeightServingSize: ALL,
			caloriesPerHundredGrams: ALL,
			gramsToServings: ['web', 'kotlin']
		},
		cases
	};
}

// --- goal rules ------------------------------------------------------------------

function goalRules(): FixtureFile {
	const cases: Case[] = [];
	const factors = [0, 0.5, 0.89, 0.9, 0.95, 1, 1.05, 1.1, 1.11, 2];
	for (const rule of ['minimum', 'maximum', 'range']) {
		for (const goal of [0, 1, 65, 2000]) {
			for (const factor of factors) {
				// The range rule compares against goal * (1 - 0.1) and goal * (1 + 0.1); building the value
				// with the same multiplication puts it exactly on those float boundaries.
				const value = goal * factor;
				cases.push(
					make('classifyGoalOutcome', `${rule}_goal${goal}_x${factor}`, { rule, value, goal })
				);
			}
		}
	}

	const goalSets: Record<string, Record<string, number>> = {
		round: {
			calorieGoal: 2000,
			proteinGoal: 150,
			carbGoal: 250,
			fatGoal: 65,
			fiberGoal: 30,
			sodiumGoal: 2300,
			sugarGoal: 50
		},
		odd: {
			calorieGoal: 1850,
			proteinGoal: 121,
			carbGoal: 203,
			fatGoal: 57,
			fiberGoal: 27,
			sodiumGoal: 2300,
			sugarGoal: 50
		},
		no_calorie_goal: {
			calorieGoal: 0,
			proteinGoal: 150,
			carbGoal: 250,
			fatGoal: 65,
			fiberGoal: 30,
			sodiumGoal: 2300,
			sugarGoal: 50
		}
	};
	const credits: [boolean, number][] = [
		[false, 100],
		[true, 0],
		[true, 33],
		[true, 50],
		[true, 100]
	];
	for (const [setName, goals] of Object.entries(goalSets)) {
		for (const activityCalories of [null, 0, -50, 1, 120, 333, 900]) {
			for (const [enabled, creditPercent] of credits) {
				const tag = `${setName}_activity${activityCalories ?? 'null'}_${enabled ? `credit${creditPercent}` : 'off'}`;
				cases.push(
					make('adjustGoalsForActivity', tag, { goals, activityCalories, enabled, creditPercent })
				);
			}
		}
	}

	return {
		$comment:
			'Generated by scripts/shared-fixtures/generate.ts from src/lib/analytics/goal-adherence.ts and src/lib/utils/activity-goals.ts: outcome classification on and around the rule boundaries, and activity-adjusted goals across credit settings.',
		tolerance: 1e-9,
		implementations: {
			classifyGoalOutcome: ['web', 'kotlin'],
			adjustGoalsForActivity: ALL
		},
		cases
	};
}

// --- meal types ------------------------------------------------------------------

/**
 * Mobile picks the default meal from the hour with 5/11/14/17 boundaries
 * (MealTiming.mealForCurrentTime on iOS, mealForCurrentTime in MealUtils.kt). The web's
 * getCurrentMealByTime uses 11/15/18 and never reaches Dinner before 18:00 or Breakfast
 * after midnight, so the platforms disagree on hours 0-4, 14 and 17. Recorded as a
 * divergence rather than hidden.
 */
const mobileMealForHour = (hour: number) =>
	hour >= 5 && hour <= 10
		? 'Breakfast'
		: hour <= 13 && hour >= 11
			? 'Lunch'
			: hour >= 14 && hour <= 16
				? 'Snacks'
				: 'Dinner';

const alphabetical = (meals: string[]) => {
	const defaults = ['Breakfast', 'Lunch', 'Dinner', 'Snacks'];
	return [
		...defaults.filter((m) => meals.includes(m)),
		...[...new Set(meals.filter((m) => !defaults.includes(m)))].sort()
	];
};

function mealTypes(): FixtureFile {
	const cases: Case[] = [];

	const spellings = [
		'breakfast',
		'Breakfast',
		'BREAKFAST',
		'lunch',
		'Lunch',
		'dinner',
		'DINNER',
		'snack',
		'Snack',
		'snacks',
		'Snacks',
		'SNACKS',
		'Brunch',
		'post-workout',
		'Mitternachtssnack',
		'Dinner ',
		' lunch',
		'Snacking'
	];
	for (const value of spellings) {
		cases.push(make('normalizeMealType', JSON.stringify(value), { value }));
	}

	for (let hour = 0; hour < 24; hour++) {
		const c = make('mealForHour', `hour_${String(hour).padStart(2, '0')}`, { hour });
		const mobile = mobileMealForHour(hour);
		if (mobile !== c.expected) {
			c.divergences = ['kotlin', 'swift'].map((platform) => ({
				platform: platform as Platform,
				expected: mobile,
				reason:
					'web getCurrentMealByTime switches at 11/15/18 h; mobile at 5/11/14/17 h (no Breakfast before 05:00, Dinner from 17:00)'
			}));
		}
		cases.push(c);
	}

	const presentSets: Record<string, string[]> = {
		defaults_in_order: ['Breakfast', 'Lunch', 'Dinner', 'Snacks'],
		defaults_reversed: ['Snacks', 'Dinner', 'Lunch', 'Breakfast'],
		only_snacks_and_breakfast: ['Snacks', 'Breakfast'],
		single_default: ['Dinner'],
		one_custom: ['Brunch'],
		custom_alphabetical: ['Brunch', 'Post-workout'],
		custom_not_alphabetical: ['Post-workout', 'Brunch'],
		customs_mixed_with_defaults: [
			'Snacks',
			'Post-workout',
			'Dinner',
			'Breakfast',
			'Lunch',
			'Brunch'
		],
		duplicates: ['Lunch', 'Lunch', 'Brunch', 'Brunch'],
		empty: []
	};
	for (const [name, present] of Object.entries(presentSets)) {
		const c = make('orderMealTypes', name, { present });
		const swift = alphabetical(present);
		if (JSON.stringify(swift) !== JSON.stringify(c.expected)) {
			c.divergences = [
				{
					platform: 'swift',
					expected: swift,
					reason:
						'web lists custom meals in the order they first appear in the day; iOS sorts them alphabetically (MealGrouping.group, WidgetSnapshotWriter.mealPrecedes)'
				}
			];
		}
		cases.push(c);
	}

	const preference = ['Lunch', 'Brunch', 'Breakfast'];
	for (const [name, present] of Object.entries({
		pref_defaults: ['Breakfast', 'Lunch', 'Dinner', 'Snacks'],
		pref_with_named_custom: ['Breakfast', 'Lunch', 'Brunch'],
		pref_unnamed_custom_goes_last: ['Breakfast', 'Post-workout', 'Dinner']
	})) {
		cases.push(make('orderMealTypesWithPreference', name, { present, mealOrder: preference }));
	}

	return {
		$comment:
			'Generated by scripts/shared-fixtures/generate.ts from src/lib/utils/meals.ts. normalizeMealType: swift is MealGrouping.canonicalKey (compared case-insensitively for the four built-ins). orderMealTypes: relative display order of the meals present in a day; Android has no shared function for it (the ordering is inline in DayLogScreen), so only web and iOS run it.',
		tolerance: 1e-9,
		implementations: {
			normalizeMealType: ALL,
			mealForHour: ALL,
			orderMealTypes: ['web', 'swift'],
			orderMealTypesWithPreference: ['web']
		},
		cases
	};
}

// --- output ----------------------------------------------------------------------

const files: Record<string, FixtureFile> = {
	'generated-unit-conversion.json': unitConversion(),
	'generated-recipe-math.json': recipeMath(),
	'generated-goal-rules.json': goalRules(),
	'generated-meal-types.json': mealTypes()
};

const checkMode = process.argv.includes('--check');
let drift = false;
for (const [name, fixture] of Object.entries(files)) {
	const path = resolve(outDir, name);
	const config = (await resolveConfig(path)) ?? {};
	const content = await format(JSON.stringify(fixture), {
		...config,
		parser: 'json',
		filepath: path
	});
	if (checkMode) {
		const current = existsSync(path) ? readFileSync(path, 'utf-8') : '';
		if (current !== content) {
			console.error(`DRIFT: ${name} is stale - run \`bun run shared:generate\``);
			drift = true;
		}
	} else {
		mkdirSync(dirname(path), { recursive: true });
		writeFileSync(path, content);
		console.log(`Wrote ${fixture.cases.length} cases to ${name}`);
	}
}
if (checkMode) {
	if (drift) process.exit(1);
	console.log('Shared fixtures are up to date.');
}
