name: Build backend Docker image (PR)

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-docker-pr.yml'
      - '.github/workflows/backend-docker-release.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set repository name to lowercase
        run: |
          echo "REPOSITORY_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: false
          tags: ghcr.io/${{ env.REPOSITORY_LC }}
