package com.bissbilanz.util

import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/**
 * Prefix used for locally generated ids before a create operation has synced and
 * received a server-assigned id. Shared across the repositories, the sync queue,
 * and the login migrator so offline-first entities can be recognized consistently.
 */
const val TEMP_PREFIX = "temp_"

/** Generates a new temp id, e.g. for an entity created offline. */
@OptIn(ExperimentalUuidApi::class)
fun newTempId(): String = "$TEMP_PREFIX${Uuid.random()}"

/** True if this id was generated by [newTempId] and has not yet been remapped to a server id. */
fun String.isTempId(): Boolean = startsWith(TEMP_PREFIX)
